### PR TITLE
feat: replace glibc with gcompat

### PR DESCRIPTION
**Pull request by greut**
> gcompat is the go-to compatibility layer for Alpine users. 
>
> https://wiki.alpinelinux.org/wiki/Running_glibc_programs

It will help with #55

### CODE REVIEW

**Comment by multani** [comment]
Oh wow, cool stuff there, thanks a lot @greut!

**Review by multani — APPROVED** [review]

**Comment by multani** [comment]
... but sadly it doesn't work with Nomad [1.5.0-beta.1](https://github.com/hashicorp/nomad/releases/tag/v1.5.0-beta.1/) from https://github.com/multani/docker-nomad/pull/75

```sh
$ docker run --rm local/nomad:1.5.0-beta.1 agent -dev
Error loading shared library libresolv.so.2: No such file or directory (needed by /bin/nomad)
```

**Comment by greut** [comment]
yup... https://github.com/hashicorp/nomad/issues/5643#issuecomment-537780347 back to square one.

**Comment by multani** [comment]
> yup... [hashicorp/nomad#5643 (comment)](https://github.com/hashicorp/nomad/issues/5643#issuecomment-537780347) back to square one.

Weird, that comment is quite old, but 1.4.2 actually starts correctly using your change :thinking:

**Pull request merged**
